# TCL File Generated by Component Editor 16.1
# Sun May 12 02:31:33 MSK 2024
# DO NOT MODIFY


# 
# integration_file "integration_file" v1.0
#  2024.05.12.02:31:33
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module integration_file
# 
set_module_property DESCRIPTION ""
set_module_property NAME integration_file
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP exam
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME integration_file
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL integration_file
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file integration_file.sv SYSTEM_VERILOG PATH integration_file.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter N INTEGER 32
set_parameter_property N DEFAULT_VALUE 32
set_parameter_property N DISPLAY_NAME N
set_parameter_property N TYPE INTEGER
set_parameter_property N UNITS None
set_parameter_property N ALLOWED_RANGES -2147483648:2147483647
set_parameter_property N HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_srst reset Input 1


# 
# connection point conduit_B
# 
add_interface conduit_B conduit end
set_interface_property conduit_B associatedClock clock
set_interface_property conduit_B associatedReset reset
set_interface_property conduit_B ENABLED true
set_interface_property conduit_B EXPORT_OF ""
set_interface_property conduit_B PORT_NAME_MAP ""
set_interface_property conduit_B CMSIS_SVD_VARIABLES ""
set_interface_property conduit_B SVD_ADDRESS_GROUP ""

add_interface_port conduit_B coe_B export Input N


# 
# connection point conduit_A
# 
add_interface conduit_A conduit end
set_interface_property conduit_A associatedClock clock
set_interface_property conduit_A associatedReset reset
set_interface_property conduit_A ENABLED true
set_interface_property conduit_A EXPORT_OF ""
set_interface_property conduit_A PORT_NAME_MAP ""
set_interface_property conduit_A CMSIS_SVD_VARIABLES ""
set_interface_property conduit_A SVD_ADDRESS_GROUP ""

add_interface_port conduit_A coe_A export Input N


# 
# connection point conduit_R
# 
add_interface conduit_R conduit end
set_interface_property conduit_R associatedClock clock
set_interface_property conduit_R associatedReset reset
set_interface_property conduit_R ENABLED true
set_interface_property conduit_R EXPORT_OF ""
set_interface_property conduit_R PORT_NAME_MAP ""
set_interface_property conduit_R CMSIS_SVD_VARIABLES ""
set_interface_property conduit_R SVD_ADDRESS_GROUP ""

add_interface_port conduit_R coe_R export Output N

