# TCL File Generated by Component Editor 16.1
# Sun May 12 01:30:15 MSK 2024
# DO NOT MODIFY


# 
# integration_file "integration_file" v1.0
#  2024.05.12.01:30:15
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module integration_file
# 
set_module_property DESCRIPTION ""
set_module_property NAME integration_file
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP exam
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME integration_file
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL integration_file
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file integration_file.sv SYSTEM_VERILOG PATH integration_file.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter N INTEGER 32
set_parameter_property N DEFAULT_VALUE 32
set_parameter_property N DISPLAY_NAME N
set_parameter_property N TYPE INTEGER
set_parameter_property N UNITS None
set_parameter_property N HDL_PARAMETER true


# 
# display items
# 


# 
# connection point in0
# 
add_interface in0 avalon_streaming end
set_interface_property in0 associatedClock clock_sink
set_interface_property in0 associatedReset reset_sink
set_interface_property in0 dataBitsPerSymbol 8
set_interface_property in0 errorDescriptor ""
set_interface_property in0 firstSymbolInHighOrderBits true
set_interface_property in0 maxChannel 0
set_interface_property in0 readyLatency 0
set_interface_property in0 ENABLED true
set_interface_property in0 EXPORT_OF ""
set_interface_property in0 PORT_NAME_MAP ""
set_interface_property in0 CMSIS_SVD_VARIABLES ""
set_interface_property in0 SVD_ADDRESS_GROUP ""

add_interface_port in0 asi_in0_data data Input N
add_interface_port in0 asi_in0_ready ready Output 1
add_interface_port in0 asi_in0_valid valid Input 1


# 
# connection point in1
# 
add_interface in1 avalon_streaming end
set_interface_property in1 associatedClock clock_sink
set_interface_property in1 associatedReset reset_sink
set_interface_property in1 dataBitsPerSymbol 8
set_interface_property in1 errorDescriptor ""
set_interface_property in1 firstSymbolInHighOrderBits true
set_interface_property in1 maxChannel 0
set_interface_property in1 readyLatency 0
set_interface_property in1 ENABLED true
set_interface_property in1 EXPORT_OF ""
set_interface_property in1 PORT_NAME_MAP ""
set_interface_property in1 CMSIS_SVD_VARIABLES ""
set_interface_property in1 SVD_ADDRESS_GROUP ""

add_interface_port in1 asi_in1_data data Input N
add_interface_port in1 asi_in1_ready ready Output 1
add_interface_port in1 asi_in1_valid valid Input 1


# 
# connection point out0
# 
add_interface out0 avalon_streaming start
set_interface_property out0 associatedClock clock_sink
set_interface_property out0 associatedReset reset_sink
set_interface_property out0 dataBitsPerSymbol 8
set_interface_property out0 errorDescriptor ""
set_interface_property out0 firstSymbolInHighOrderBits true
set_interface_property out0 maxChannel 0
set_interface_property out0 readyLatency 0
set_interface_property out0 ENABLED true
set_interface_property out0 EXPORT_OF ""
set_interface_property out0 PORT_NAME_MAP ""
set_interface_property out0 CMSIS_SVD_VARIABLES ""
set_interface_property out0 SVD_ADDRESS_GROUP ""

add_interface_port out0 aso_out0_data data Output N
add_interface_port out0 aso_out0_ready ready Input 1
add_interface_port out0 aso_out0_valid valid Output 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset_reset reset Input 1

